# NUMPY BASICS

In [1]:
import numpy as np

In [2]:
 myarr=np.array([[3,6,32,7]], np.int32)

In [3]:
myarr

array([[ 3,  6, 32,  7]], dtype=int32)

In [4]:
myarr[0,2]

32

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr[0,1]=45

In [8]:
myarr

array([[ 3, 45, 32,  7]], dtype=int32)

# conversion from other python structures

In [12]:
listarray=np.array([[3,4,6],[7,8,9],[4,0,1]])

In [13]:
listarray

array([[3, 4, 6],
       [7, 8, 9],
       [4, 0, 1]])

In [14]:
listarray.dtype

dtype('int64')

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray.size

9

In [17]:
np.array({34,45,65})

array({65, 34, 45}, dtype=object)

In [18]:
zeros=np.zeros((2,4))

In [19]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
 rng= np.arange(15)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
lspace=np.linspace(1,2,4)

In [36]:
lspace

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [37]:
lspace=np.linspace(1,4,8)

In [38]:
lspace

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [39]:
emp = np.empty((4,6))

In [40]:
emp

array([[0.00000000e+000, 6.76869935e-322, 0.00000000e+000,
        0.00000000e+000, 1.29441743e-312, 5.30276956e+180],
       [6.00736842e-067, 4.95296725e+097, 3.31786574e-033,
        3.24857155e+126, 4.25223142e+180, 7.48543529e+247],
       [2.32363010e+251, 6.11130817e+223, 2.59903818e-144,
        2.34444169e-056, 9.04747680e-043, 6.50095417e-091],
       [4.50738753e+174, 2.59027863e-144, 1.16442250e-028,
        9.44872517e-143, 6.17582057e-322, 0.00000000e+000]])

In [41]:
emp_like=np.empty_like(lspace)

In [42]:
emp_like

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [43]:
ide=np.identity(45)

In [44]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [45]:
ide.shape

(45, 45)

In [46]:
 ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [51]:
myarr

array([[ 3, 45, 32,  7]], dtype=int32)

In [52]:
x=[[1,2,3],[2,3,4],[5,6,7]]

In [54]:
ar=np.array(x)

In [55]:
ar

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [56]:
ar.sum(axis=0)

array([ 8, 11, 14])

In [57]:
ar.nbytes

72

In [58]:
one = np.array([63,4,5,66,7,6])

In [60]:
one.argmax()

3

In [61]:
one.argmin()

1